meta_title: "piXXer - Own the night"
meta_description: "Party with like minded people you've never met"
meta_image: "homepage_to_change.jpg" # Replace with homepage image app/assets/images/
twitter_account: "@lewagonbrussels" # indispensable pour les Twitter Cards
